ALBS-259 Disable adding unsigned builds to release
AlmaLinux/albs-frontend pull request #154
Opened 2022-04-07 10:46 UTC by maccelf

2022-04-07 15:07 UTC, maccelf commented on src/components/BuildSelectionForm.vue
> +                            message: `Build ${buildId} does not signed`,
Yea, thank you

2022-04-07 16:06 UTC, anfimovdm requested changes

2022-04-07 16:34 UTC, anfimovdm approved these changes

2022-04-08 11:11 UTC, AvoidMe approved these changes

2022-04-08 11:12 UTC, Korulag approved these changes

2022-04-08 11:13 UTC, merged