ALBS-304 Fix incorrect hint when remove a build from a distribution
AlmaLinux/albs-frontend pull request #164
Opened 2022-04-21 12:36 UTC by maccelf

2022-04-21 12:45 UTC, Korulag requested changes

2022-04-21 12:45 UTC, Korulag commented on src/pages/Build.vue
> +            <q-select v-model="current_distro" label="Choose distribution to add"
"to add" -> "to add to"

2022-04-21 12:45 UTC, Korulag commented on src/pages/Build.vue
> +            <q-select v-model="current_distro" label="Choose distribution to remove"
"to remove" -> "to remove from"

2022-04-21 13:09 UTC, soksanichenko approved these changes

2022-04-22 08:18 UTC, AvoidMe approved these changes

2022-04-22 08:30 UTC, anfimovdm approved these changes

2022-04-22 08:41 UTC, merged