Test system UI
AlmaLinux/albs-frontend pull request #43
Opened 2021-11-02 11:52 UTC by oweel

2021-11-03 08:53 UTC, anfimovdm requested changes

2021-11-03 08:53 UTC, anfimovdm commented on src/constants.js
> +    3: 'tests failed'
Why keys repeated?

2021-11-03 11:13 UTC, oweel commented on src/constants.js
> +    3: 'tests failed'
Fixed

2021-11-12 17:08 UTC, Korulag commented
Is done in another PR

2021-11-12 17:08 UTC, closed without merging