Create endpoint to reset package mappings of unreleased erratas
AlmaLinux/albs-frontend pull request #504
Opened 2024-08-02 13:15 UTC by Kwaizer

Resolves: https://github.com/AlmaLinux/build-system/issues/308

- Added an ability to choose an issue_date of erratas

![image](https://github.com/user-attachments/assets/b361dae5-3f0a-4a28-8331-f2f61725cd4e)

Backend: https://github.com/AlmaLinux/albs-web-server/pull/929

2024-08-05 13:42 UTC, anfimovdm requested changes

2024-08-05 13:42 UTC, anfimovdm commented on src/pages/ErrataFeed.vue
> +      </div>
I don't think that place under the page count is the best one

2024-08-09 11:54 UTC, anfimovdm approved these changes

2024-08-15 15:07 UTC, maccelf commented
Could you please do something like this ? 
![Screenshot from 2024-08-15 17-06-21](https://github.com/user-attachments/assets/fc05faeb-06de-4811-9e30-837a074ccb0b)
![Screenshot from 2024-08-15 17-06-27](https://github.com/user-attachments/assets/6322b0aa-282c-4333-aa34-c8f0a81b22f1)

2024-08-15 17:54 UTC, maccelf requested changes

2024-08-15 17:54 UTC, maccelf commented on src/pages/ErrataFeed.vue
> +        <template v-slot:top-right>
Please show this section only for authorized users

2024-08-15 17:54 UTC, maccelf commented on src/pages/ErrataFeed.vue
> +                    style="
Use the style section below to define a new class and set it to the class section for the element

2024-08-15 17:54 UTC, maccelf commented on src/pages/ErrataFeed.vue
> +          <q-dialog v-model="showDialogAdvisories">
Please move this `<q-dialog>` at row 157 (after last `</div>`)

2024-08-15 17:54 UTC, maccelf commented on src/pages/ErrataFeed.vue
> +            :loading="loadingReset"
Move loading from this button to button in dialog

2024-08-16 15:22 UTC, maccelf requested changes

2024-08-16 15:22 UTC, maccelf commented on src/pages/ErrataFeed.vue
> +        <q-tooltip>
Please remove one of the tooltips do the correct indent and make sure that everything works fine

2024-08-16 15:34 UTC, maccelf approved these changes

2024-08-28 07:36 UTC, merged