Add bulk releases to Errata Feed
AlmaLinux/albs-frontend pull request #534
Opened 2024-10-15 20:56 UTC by bklvsky

Resolves: AlmaLinux/build-system#325

2024-10-16 12:09 UTC, soksanichenko approved these changes

2024-10-23 18:06 UTC, maccelf requested changes

2024-10-25 08:06 UTC, maccelf requested changes
Please do a rebase

2024-11-04 09:15 UTC, maccelf requested changes

2024-11-04 09:15 UTC, maccelf commented on src/pages/ErrataFeed.vue
> +                v-if="col.name === 'id'"
```suggestion
                v-if="col.name === 'id' && userAuthenticated()"
```

2024-11-20 15:49 UTC, merged