Adding platforms to products to UI
AlmaLinux/albs-frontend pull request #538
Opened 2024-10-21 19:40 UTC by bklvsky

Resolves: AlmaLinux/build-system#359

2024-10-24 16:05 UTC, maccelf requested changes

2024-10-24 16:05 UTC, maccelf commented on src/pages/ProductDetails.vue
>            </q-card-actions>
Please do something like this:
```suggestion
          <q-card-actions class="justify-end q-pr-sm">
            <div class="q-gutter-md">
              <q-skeleton type="circle" v-if="loadingPage" />
              <q-btn
                @click="enablePlatforms()"
                color="primary"
                :loading="loadingPlatform"
                round
                icon="format_list_bulleted_add"
              >
                <q-tooltip> Add platforms to product </q-tooltip>
              </q-btn>
              <q-skeleton type="circle" v-if="loadingPage" />
              <q-btn
                v-else
                color="negative"
                icon="delete"
                round
                @click="confirm = true"
                :disable="loadingPlatform"
                :loading="loading"
              >
                <q-tooltip> Delete product </q-tooltip>
              </q-btn>
            </div>
          </q-card-actions>
```

2024-10-24 16:05 UTC, maccelf commented on src/pages/ProductDetails.vue
> +        <div v-if="platformsEnabled">
Please do a `q-dialog` instead

2024-11-04 09:17 UTC, maccelf approved these changes

2024-11-04 09:22 UTC, anfimovdm approved these changes

2024-11-04 09:23 UTC, merged