ALBS-94 Add UI for signing builds
AlmaLinux/albs-frontend pull request #83
Opened 2021-12-10 12:04 UTC by maccelf

2021-12-13 09:57 UTC, anfimovdm requested changes

2021-12-13 09:57 UTC, anfimovdm commented on src/pages/Build.vue
> +                    <q-btn v-if="sign.status===3" icon="cached" color="faded"
Use `SignStatus` enum than digits

2021-12-14 13:05 UTC, maccelf commented on src/pages/Build.vue
> +                    <q-btn v-if="sign.status===3" icon="cached" color="faded"
Fixed

2021-12-14 13:07 UTC, anfimovdm approved these changes

2022-01-19 15:12 UTC, merged